// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tcc_coordinator.proto

/*
	Package contract is a generated protocol buffer package.

	It is generated from these files:
		tcc_coordinator.proto

	It has these top-level messages:
		TransactionId
		TransactionStep
		Transaction
		BeginTransRequest
		BeginTransResponse
		TryStepRequest
		TryStepResponse
		ConfirmTransRequest
		ConfirmTransResponse
		CancelTransRequest
		CancelTransResponse
		CancelTransSuccessRequest
		CancelTransSuccessResponse
		GetTransRequest
		GetTransResponse
		GetExpiredTransListRequest
		GetExpiredTransListResponse
		GetRollingBackTransListRequest
		GetRollingBackTransListResponse
*/
package contract

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Transaction_TransactionStatus int32

const (
	Transaction_Init        Transaction_TransactionStatus = 0
	Transaction_Committed   Transaction_TransactionStatus = 10
	Transaction_RollingBack Transaction_TransactionStatus = 20
	Transaction_RolledBack  Transaction_TransactionStatus = 40
)

var Transaction_TransactionStatus_name = map[int32]string{
	0:  "Init",
	10: "Committed",
	20: "RollingBack",
	40: "RolledBack",
}
var Transaction_TransactionStatus_value = map[string]int32{
	"Init":        0,
	"Committed":   10,
	"RollingBack": 20,
	"RolledBack":  40,
}

func (x Transaction_TransactionStatus) String() string {
	return proto.EnumName(Transaction_TransactionStatus_name, int32(x))
}
func (Transaction_TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{2, 0}
}

type BeginTransResponse_BeginTransResponseErrorCode int32

const (
	BeginTransResponse_OK               BeginTransResponse_BeginTransResponseErrorCode = 0
	BeginTransResponse_InvalidAppId     BeginTransResponse_BeginTransResponseErrorCode = 1
	BeginTransResponse_EmptyBusCode     BeginTransResponse_BeginTransResponseErrorCode = 2
	BeginTransResponse_EmptyTRXId       BeginTransResponse_BeginTransResponseErrorCode = 3
	BeginTransResponse_DuplicateRequest BeginTransResponse_BeginTransResponseErrorCode = 10
)

var BeginTransResponse_BeginTransResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "InvalidAppId",
	2:  "EmptyBusCode",
	3:  "EmptyTRXId",
	10: "DuplicateRequest",
}
var BeginTransResponse_BeginTransResponseErrorCode_value = map[string]int32{
	"OK":               0,
	"InvalidAppId":     1,
	"EmptyBusCode":     2,
	"EmptyTRXId":       3,
	"DuplicateRequest": 10,
}

func (x BeginTransResponse_BeginTransResponseErrorCode) String() string {
	return proto.EnumName(BeginTransResponse_BeginTransResponseErrorCode_name, int32(x))
}
func (BeginTransResponse_BeginTransResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{4, 0}
}

type TryStepResponse_TryStepResponseErrorCode int32

const (
	TryStepResponse_OK                     TryStepResponse_TryStepResponseErrorCode = 0
	TryStepResponse_EmptyTransUniqId       TryStepResponse_TryStepResponseErrorCode = 1
	TryStepResponse_EmptyStepId            TryStepResponse_TryStepResponseErrorCode = 2
	TryStepResponse_TransactionNotFound    TryStepResponse_TryStepResponseErrorCode = 10
	TryStepResponse_TransactionStatusError TryStepResponse_TryStepResponseErrorCode = 11
)

var TryStepResponse_TryStepResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "EmptyTransUniqId",
	2:  "EmptyStepId",
	10: "TransactionNotFound",
	11: "TransactionStatusError",
}
var TryStepResponse_TryStepResponseErrorCode_value = map[string]int32{
	"OK":                     0,
	"EmptyTransUniqId":       1,
	"EmptyStepId":            2,
	"TransactionNotFound":    10,
	"TransactionStatusError": 11,
}

func (x TryStepResponse_TryStepResponseErrorCode) String() string {
	return proto.EnumName(TryStepResponse_TryStepResponseErrorCode_name, int32(x))
}
func (TryStepResponse_TryStepResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{6, 0}
}

type ConfirmTransResponse_ConfirmTransResponseErrorCode int32

const (
	ConfirmTransResponse_OK                     ConfirmTransResponse_ConfirmTransResponseErrorCode = 0
	ConfirmTransResponse_EmptyTransUniqId       ConfirmTransResponse_ConfirmTransResponseErrorCode = 1
	ConfirmTransResponse_TransactionNotFound    ConfirmTransResponse_ConfirmTransResponseErrorCode = 10
	ConfirmTransResponse_TransactionStatusError ConfirmTransResponse_ConfirmTransResponseErrorCode = 11
)

var ConfirmTransResponse_ConfirmTransResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "EmptyTransUniqId",
	10: "TransactionNotFound",
	11: "TransactionStatusError",
}
var ConfirmTransResponse_ConfirmTransResponseErrorCode_value = map[string]int32{
	"OK":                     0,
	"EmptyTransUniqId":       1,
	"TransactionNotFound":    10,
	"TransactionStatusError": 11,
}

func (x ConfirmTransResponse_ConfirmTransResponseErrorCode) String() string {
	return proto.EnumName(ConfirmTransResponse_ConfirmTransResponseErrorCode_name, int32(x))
}
func (ConfirmTransResponse_ConfirmTransResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{8, 0}
}

type CancelTransResponse_ConfirmTransResponseErrorCode int32

const (
	CancelTransResponse_OK                     CancelTransResponse_ConfirmTransResponseErrorCode = 0
	CancelTransResponse_EmptyTransUniqId       CancelTransResponse_ConfirmTransResponseErrorCode = 1
	CancelTransResponse_TransactionNotFound    CancelTransResponse_ConfirmTransResponseErrorCode = 10
	CancelTransResponse_TransactionStatusError CancelTransResponse_ConfirmTransResponseErrorCode = 11
)

var CancelTransResponse_ConfirmTransResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "EmptyTransUniqId",
	10: "TransactionNotFound",
	11: "TransactionStatusError",
}
var CancelTransResponse_ConfirmTransResponseErrorCode_value = map[string]int32{
	"OK":                     0,
	"EmptyTransUniqId":       1,
	"TransactionNotFound":    10,
	"TransactionStatusError": 11,
}

func (x CancelTransResponse_ConfirmTransResponseErrorCode) String() string {
	return proto.EnumName(CancelTransResponse_ConfirmTransResponseErrorCode_name, int32(x))
}
func (CancelTransResponse_ConfirmTransResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{10, 0}
}

type CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode int32

const (
	CancelTransSuccessResponse_OK                     CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode = 0
	CancelTransSuccessResponse_EmptyTransUniqId       CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode = 1
	CancelTransSuccessResponse_TransactionNotFound    CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode = 10
	CancelTransSuccessResponse_TransactionStatusError CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode = 11
)

var CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "EmptyTransUniqId",
	10: "TransactionNotFound",
	11: "TransactionStatusError",
}
var CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode_value = map[string]int32{
	"OK":                     0,
	"EmptyTransUniqId":       1,
	"TransactionNotFound":    10,
	"TransactionStatusError": 11,
}

func (x CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode) String() string {
	return proto.EnumName(CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode_name, int32(x))
}
func (CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{12, 0}
}

type GetTransResponse_GetTransResponseErrorCode int32

const (
	GetTransResponse_OK                 GetTransResponse_GetTransResponseErrorCode = 0
	GetTransResponse_InvalidAppId       GetTransResponse_GetTransResponseErrorCode = 1
	GetTransResponse_EmptyBusCode       GetTransResponse_GetTransResponseErrorCode = 2
	GetTransResponse_EmptyTRXId         GetTransResponse_GetTransResponseErrorCode = 3
	GetTransResponse_InvalidTransUniqId GetTransResponse_GetTransResponseErrorCode = 10
)

var GetTransResponse_GetTransResponseErrorCode_name = map[int32]string{
	0:  "OK",
	1:  "InvalidAppId",
	2:  "EmptyBusCode",
	3:  "EmptyTRXId",
	10: "InvalidTransUniqId",
}
var GetTransResponse_GetTransResponseErrorCode_value = map[string]int32{
	"OK":                 0,
	"InvalidAppId":       1,
	"EmptyBusCode":       2,
	"EmptyTRXId":         3,
	"InvalidTransUniqId": 10,
}

func (x GetTransResponse_GetTransResponseErrorCode) String() string {
	return proto.EnumName(GetTransResponse_GetTransResponseErrorCode_name, int32(x))
}
func (GetTransResponse_GetTransResponseErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{14, 0}
}

type TransactionId struct {
	// Identifier of app
	AppId string `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	// Business Code
	BusCode string `protobuf:"bytes,2,opt,name=busCode,proto3" json:"busCode,omitempty"`
	// Business transactionId
	TrxId string `protobuf:"bytes,3,opt,name=trxId,proto3" json:"trxId,omitempty"`
}

func (m *TransactionId) Reset()                    { *m = TransactionId{} }
func (m *TransactionId) String() string            { return proto.CompactTextString(m) }
func (*TransactionId) ProtoMessage()               {}
func (*TransactionId) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{0} }

func (m *TransactionId) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *TransactionId) GetBusCode() string {
	if m != nil {
		return m.BusCode
	}
	return ""
}

func (m *TransactionId) GetTrxId() string {
	if m != nil {
		return m.TrxId
	}
	return ""
}

type TransactionStep struct {
	StepId string `protobuf:"bytes,1,opt,name=stepId,proto3" json:"stepId,omitempty"`
	Args   []byte `protobuf:"bytes,2,opt,name=Args,proto3" json:"Args,omitempty"`
}

func (m *TransactionStep) Reset()                    { *m = TransactionStep{} }
func (m *TransactionStep) String() string            { return proto.CompactTextString(m) }
func (*TransactionStep) ProtoMessage()               {}
func (*TransactionStep) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{1} }

func (m *TransactionStep) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *TransactionStep) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type Transaction struct {
	TransactionId *TransactionId                `protobuf:"bytes,1,opt,name=transactionId" json:"transactionId,omitempty"`
	TransUniqId   string                        `protobuf:"bytes,2,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
	Steps         []*TransactionStep            `protobuf:"bytes,3,rep,name=steps" json:"steps,omitempty"`
	Status        Transaction_TransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=softtrans.coordinator.tcc.Transaction_TransactionStatus" json:"status,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{2} }

func (m *Transaction) GetTransactionId() *TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *Transaction) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

func (m *Transaction) GetSteps() []*TransactionStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Transaction) GetStatus() Transaction_TransactionStatus {
	if m != nil {
		return m.Status
	}
	return Transaction_Init
}

type BeginTransRequest struct {
	TransactionId *TransactionId `protobuf:"bytes,1,opt,name=transactionId" json:"transactionId,omitempty"`
	// 为true时，如果协调器发现已经有相同TransactionId的事务存在，将返回错误 DuplicateRequest
	// 为false时，如果协调器发现已经有相同TransactionId的事务存在，将返回已经存在的事务
	FailFast bool `protobuf:"varint,2,opt,name=failFast,proto3" json:"failFast,omitempty"`
	// 事务过期时长(单位:秒)
	ExpireTimeSeconds int32 `protobuf:"varint,3,opt,name=expireTimeSeconds,proto3" json:"expireTimeSeconds,omitempty"`
}

func (m *BeginTransRequest) Reset()                    { *m = BeginTransRequest{} }
func (m *BeginTransRequest) String() string            { return proto.CompactTextString(m) }
func (*BeginTransRequest) ProtoMessage()               {}
func (*BeginTransRequest) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{3} }

func (m *BeginTransRequest) GetTransactionId() *TransactionId {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func (m *BeginTransRequest) GetFailFast() bool {
	if m != nil {
		return m.FailFast
	}
	return false
}

func (m *BeginTransRequest) GetExpireTimeSeconds() int32 {
	if m != nil {
		return m.ExpireTimeSeconds
	}
	return 0
}

type BeginTransResponse struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *BeginTransResponse) Reset()                    { *m = BeginTransResponse{} }
func (m *BeginTransResponse) String() string            { return proto.CompactTextString(m) }
func (*BeginTransResponse) ProtoMessage()               {}
func (*BeginTransResponse) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{4} }

func (m *BeginTransResponse) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type TryStepRequest struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
	StepId      string `protobuf:"bytes,2,opt,name=stepId,proto3" json:"stepId,omitempty"`
	Args        []byte `protobuf:"bytes,3,opt,name=Args,proto3" json:"Args,omitempty"`
}

func (m *TryStepRequest) Reset()                    { *m = TryStepRequest{} }
func (m *TryStepRequest) String() string            { return proto.CompactTextString(m) }
func (*TryStepRequest) ProtoMessage()               {}
func (*TryStepRequest) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{5} }

func (m *TryStepRequest) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

func (m *TryStepRequest) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *TryStepRequest) GetArgs() []byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type TryStepResponse struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
	StepId      string `protobuf:"bytes,2,opt,name=stepId,proto3" json:"stepId,omitempty"`
}

func (m *TryStepResponse) Reset()                    { *m = TryStepResponse{} }
func (m *TryStepResponse) String() string            { return proto.CompactTextString(m) }
func (*TryStepResponse) ProtoMessage()               {}
func (*TryStepResponse) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{6} }

func (m *TryStepResponse) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

func (m *TryStepResponse) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

type ConfirmTransRequest struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *ConfirmTransRequest) Reset()         { *m = ConfirmTransRequest{} }
func (m *ConfirmTransRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransRequest) ProtoMessage()    {}
func (*ConfirmTransRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{7}
}

func (m *ConfirmTransRequest) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type ConfirmTransResponse struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *ConfirmTransResponse) Reset()         { *m = ConfirmTransResponse{} }
func (m *ConfirmTransResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransResponse) ProtoMessage()    {}
func (*ConfirmTransResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{8}
}

func (m *ConfirmTransResponse) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type CancelTransRequest struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *CancelTransRequest) Reset()                    { *m = CancelTransRequest{} }
func (m *CancelTransRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelTransRequest) ProtoMessage()               {}
func (*CancelTransRequest) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{9} }

func (m *CancelTransRequest) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type CancelTransResponse struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *CancelTransResponse) Reset()         { *m = CancelTransResponse{} }
func (m *CancelTransResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTransResponse) ProtoMessage()    {}
func (*CancelTransResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{10}
}

func (m *CancelTransResponse) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type CancelTransSuccessRequest struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *CancelTransSuccessRequest) Reset()         { *m = CancelTransSuccessRequest{} }
func (m *CancelTransSuccessRequest) String() string { return proto.CompactTextString(m) }
func (*CancelTransSuccessRequest) ProtoMessage()    {}
func (*CancelTransSuccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{11}
}

func (m *CancelTransSuccessRequest) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type CancelTransSuccessResponse struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *CancelTransSuccessResponse) Reset()         { *m = CancelTransSuccessResponse{} }
func (m *CancelTransSuccessResponse) String() string { return proto.CompactTextString(m) }
func (*CancelTransSuccessResponse) ProtoMessage()    {}
func (*CancelTransSuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{12}
}

func (m *CancelTransSuccessResponse) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type GetTransRequest struct {
	TransUniqId string `protobuf:"bytes,1,opt,name=transUniqId,proto3" json:"transUniqId,omitempty"`
}

func (m *GetTransRequest) Reset()                    { *m = GetTransRequest{} }
func (m *GetTransRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTransRequest) ProtoMessage()               {}
func (*GetTransRequest) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{13} }

func (m *GetTransRequest) GetTransUniqId() string {
	if m != nil {
		return m.TransUniqId
	}
	return ""
}

type GetTransResponse struct {
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
}

func (m *GetTransResponse) Reset()                    { *m = GetTransResponse{} }
func (m *GetTransResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTransResponse) ProtoMessage()               {}
func (*GetTransResponse) Descriptor() ([]byte, []int) { return fileDescriptorTccCoordinator, []int{14} }

func (m *GetTransResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type GetExpiredTransListRequest struct {
	TopN int32 `protobuf:"varint,1,opt,name=topN,proto3" json:"topN,omitempty"`
}

func (m *GetExpiredTransListRequest) Reset()         { *m = GetExpiredTransListRequest{} }
func (m *GetExpiredTransListRequest) String() string { return proto.CompactTextString(m) }
func (*GetExpiredTransListRequest) ProtoMessage()    {}
func (*GetExpiredTransListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{15}
}

func (m *GetExpiredTransListRequest) GetTopN() int32 {
	if m != nil {
		return m.TopN
	}
	return 0
}

type GetExpiredTransListResponse struct {
	TransUniqIds []string `protobuf:"bytes,1,rep,name=transUniqIds" json:"transUniqIds,omitempty"`
}

func (m *GetExpiredTransListResponse) Reset()         { *m = GetExpiredTransListResponse{} }
func (m *GetExpiredTransListResponse) String() string { return proto.CompactTextString(m) }
func (*GetExpiredTransListResponse) ProtoMessage()    {}
func (*GetExpiredTransListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{16}
}

func (m *GetExpiredTransListResponse) GetTransUniqIds() []string {
	if m != nil {
		return m.TransUniqIds
	}
	return nil
}

type GetRollingBackTransListRequest struct {
	TopN int32 `protobuf:"varint,1,opt,name=topN,proto3" json:"topN,omitempty"`
}

func (m *GetRollingBackTransListRequest) Reset()         { *m = GetRollingBackTransListRequest{} }
func (m *GetRollingBackTransListRequest) String() string { return proto.CompactTextString(m) }
func (*GetRollingBackTransListRequest) ProtoMessage()    {}
func (*GetRollingBackTransListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{17}
}

func (m *GetRollingBackTransListRequest) GetTopN() int32 {
	if m != nil {
		return m.TopN
	}
	return 0
}

type GetRollingBackTransListResponse struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *GetRollingBackTransListResponse) Reset()         { *m = GetRollingBackTransListResponse{} }
func (m *GetRollingBackTransListResponse) String() string { return proto.CompactTextString(m) }
func (*GetRollingBackTransListResponse) ProtoMessage()    {}
func (*GetRollingBackTransListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorTccCoordinator, []int{18}
}

func (m *GetRollingBackTransListResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionId)(nil), "softtrans.coordinator.tcc.TransactionId")
	proto.RegisterType((*TransactionStep)(nil), "softtrans.coordinator.tcc.TransactionStep")
	proto.RegisterType((*Transaction)(nil), "softtrans.coordinator.tcc.Transaction")
	proto.RegisterType((*BeginTransRequest)(nil), "softtrans.coordinator.tcc.BeginTransRequest")
	proto.RegisterType((*BeginTransResponse)(nil), "softtrans.coordinator.tcc.BeginTransResponse")
	proto.RegisterType((*TryStepRequest)(nil), "softtrans.coordinator.tcc.TryStepRequest")
	proto.RegisterType((*TryStepResponse)(nil), "softtrans.coordinator.tcc.TryStepResponse")
	proto.RegisterType((*ConfirmTransRequest)(nil), "softtrans.coordinator.tcc.ConfirmTransRequest")
	proto.RegisterType((*ConfirmTransResponse)(nil), "softtrans.coordinator.tcc.ConfirmTransResponse")
	proto.RegisterType((*CancelTransRequest)(nil), "softtrans.coordinator.tcc.CancelTransRequest")
	proto.RegisterType((*CancelTransResponse)(nil), "softtrans.coordinator.tcc.CancelTransResponse")
	proto.RegisterType((*CancelTransSuccessRequest)(nil), "softtrans.coordinator.tcc.CancelTransSuccessRequest")
	proto.RegisterType((*CancelTransSuccessResponse)(nil), "softtrans.coordinator.tcc.CancelTransSuccessResponse")
	proto.RegisterType((*GetTransRequest)(nil), "softtrans.coordinator.tcc.GetTransRequest")
	proto.RegisterType((*GetTransResponse)(nil), "softtrans.coordinator.tcc.GetTransResponse")
	proto.RegisterType((*GetExpiredTransListRequest)(nil), "softtrans.coordinator.tcc.GetExpiredTransListRequest")
	proto.RegisterType((*GetExpiredTransListResponse)(nil), "softtrans.coordinator.tcc.GetExpiredTransListResponse")
	proto.RegisterType((*GetRollingBackTransListRequest)(nil), "softtrans.coordinator.tcc.GetRollingBackTransListRequest")
	proto.RegisterType((*GetRollingBackTransListResponse)(nil), "softtrans.coordinator.tcc.GetRollingBackTransListResponse")
	proto.RegisterEnum("softtrans.coordinator.tcc.Transaction_TransactionStatus", Transaction_TransactionStatus_name, Transaction_TransactionStatus_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.BeginTransResponse_BeginTransResponseErrorCode", BeginTransResponse_BeginTransResponseErrorCode_name, BeginTransResponse_BeginTransResponseErrorCode_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.TryStepResponse_TryStepResponseErrorCode", TryStepResponse_TryStepResponseErrorCode_name, TryStepResponse_TryStepResponseErrorCode_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.ConfirmTransResponse_ConfirmTransResponseErrorCode", ConfirmTransResponse_ConfirmTransResponseErrorCode_name, ConfirmTransResponse_ConfirmTransResponseErrorCode_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.CancelTransResponse_ConfirmTransResponseErrorCode", CancelTransResponse_ConfirmTransResponseErrorCode_name, CancelTransResponse_ConfirmTransResponseErrorCode_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode", CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode_name, CancelTransSuccessResponse_ConfirmTransSuccessResponseErrorCode_value)
	proto.RegisterEnum("softtrans.coordinator.tcc.GetTransResponse_GetTransResponseErrorCode", GetTransResponse_GetTransResponseErrorCode_name, GetTransResponse_GetTransResponseErrorCode_value)
}
func (m *TransactionId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionId) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.AppId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.AppId)))
		i += copy(dAtA[i:], m.AppId)
	}
	if len(m.BusCode) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.BusCode)))
		i += copy(dAtA[i:], m.BusCode)
	}
	if len(m.TrxId) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TrxId)))
		i += copy(dAtA[i:], m.TrxId)
	}
	return i, nil
}

func (m *TransactionStep) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionStep) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.StepId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.StepId)))
		i += copy(dAtA[i:], m.StepId)
	}
	if len(m.Args) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.Args)))
		i += copy(dAtA[i:], m.Args)
	}
	return i, nil
}

func (m *Transaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Transaction) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TransactionId != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.TransactionId.Size()))
		n1, err := m.TransactionId.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	if len(m.Steps) > 0 {
		for _, msg := range m.Steps {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintTccCoordinator(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Status != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func (m *BeginTransRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BeginTransRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TransactionId != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.TransactionId.Size()))
		n2, err := m.TransactionId.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.FailFast {
		dAtA[i] = 0x10
		i++
		if m.FailFast {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.ExpireTimeSeconds != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.ExpireTimeSeconds))
	}
	return i, nil
}

func (m *BeginTransResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BeginTransResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *TryStepRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TryStepRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	if len(m.StepId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.StepId)))
		i += copy(dAtA[i:], m.StepId)
	}
	if len(m.Args) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.Args)))
		i += copy(dAtA[i:], m.Args)
	}
	return i, nil
}

func (m *TryStepResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TryStepResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	if len(m.StepId) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.StepId)))
		i += copy(dAtA[i:], m.StepId)
	}
	return i, nil
}

func (m *ConfirmTransRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfirmTransRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *ConfirmTransResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfirmTransResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *CancelTransRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelTransRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *CancelTransResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelTransResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *CancelTransSuccessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelTransSuccessRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *CancelTransSuccessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CancelTransSuccessResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *GetTransRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTransRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqId) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(len(m.TransUniqId)))
		i += copy(dAtA[i:], m.TransUniqId)
	}
	return i, nil
}

func (m *GetTransResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetTransResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Transaction != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.Transaction.Size()))
		n3, err := m.Transaction.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *GetExpiredTransListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetExpiredTransListRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TopN != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.TopN))
	}
	return i, nil
}

func (m *GetExpiredTransListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetExpiredTransListResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TransUniqIds) > 0 {
		for _, s := range m.TransUniqIds {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *GetRollingBackTransListRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRollingBackTransListRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TopN != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintTccCoordinator(dAtA, i, uint64(m.TopN))
	}
	return i, nil
}

func (m *GetRollingBackTransListResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRollingBackTransListResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, msg := range m.Transactions {
			dAtA[i] = 0xa
			i++
			i = encodeVarintTccCoordinator(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintTccCoordinator(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TransactionId) Size() (n int) {
	var l int
	_ = l
	l = len(m.AppId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.BusCode)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.TrxId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *TransactionStep) Size() (n int) {
	var l int
	_ = l
	l = len(m.StepId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.Args)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *Transaction) Size() (n int) {
	var l int
	_ = l
	if m.TransactionId != nil {
		l = m.TransactionId.Size()
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	if len(m.Steps) > 0 {
		for _, e := range m.Steps {
			l = e.Size()
			n += 1 + l + sovTccCoordinator(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovTccCoordinator(uint64(m.Status))
	}
	return n
}

func (m *BeginTransRequest) Size() (n int) {
	var l int
	_ = l
	if m.TransactionId != nil {
		l = m.TransactionId.Size()
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	if m.FailFast {
		n += 2
	}
	if m.ExpireTimeSeconds != 0 {
		n += 1 + sovTccCoordinator(uint64(m.ExpireTimeSeconds))
	}
	return n
}

func (m *BeginTransResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *TryStepRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.StepId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.Args)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *TryStepResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	l = len(m.StepId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *ConfirmTransRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *ConfirmTransResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *CancelTransRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *CancelTransResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *CancelTransSuccessRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *CancelTransSuccessResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *GetTransRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.TransUniqId)
	if l > 0 {
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *GetTransResponse) Size() (n int) {
	var l int
	_ = l
	if m.Transaction != nil {
		l = m.Transaction.Size()
		n += 1 + l + sovTccCoordinator(uint64(l))
	}
	return n
}

func (m *GetExpiredTransListRequest) Size() (n int) {
	var l int
	_ = l
	if m.TopN != 0 {
		n += 1 + sovTccCoordinator(uint64(m.TopN))
	}
	return n
}

func (m *GetExpiredTransListResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.TransUniqIds) > 0 {
		for _, s := range m.TransUniqIds {
			l = len(s)
			n += 1 + l + sovTccCoordinator(uint64(l))
		}
	}
	return n
}

func (m *GetRollingBackTransListRequest) Size() (n int) {
	var l int
	_ = l
	if m.TopN != 0 {
		n += 1 + sovTccCoordinator(uint64(m.TopN))
	}
	return n
}

func (m *GetRollingBackTransListResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Transactions) > 0 {
		for _, e := range m.Transactions {
			l = e.Size()
			n += 1 + l + sovTccCoordinator(uint64(l))
		}
	}
	return n
}

func sovTccCoordinator(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTccCoordinator(x uint64) (n int) {
	return sovTccCoordinator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TransactionId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TransactionStep) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionStep: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionStep: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StepId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StepId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args[:0], dAtA[iNdEx:postIndex]...)
			if m.Args == nil {
				m.Args = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Transaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Transaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Transaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransactionId == nil {
				m.TransactionId = &TransactionId{}
			}
			if err := m.TransactionId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Steps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Steps = append(m.Steps, &TransactionStep{})
			if err := m.Steps[len(m.Steps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (Transaction_TransactionStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BeginTransRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BeginTransRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BeginTransRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TransactionId == nil {
				m.TransactionId = &TransactionId{}
			}
			if err := m.TransactionId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailFast", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FailFast = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireTimeSeconds", wireType)
			}
			m.ExpireTimeSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpireTimeSeconds |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BeginTransResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BeginTransResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BeginTransResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TryStepRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TryStepRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TryStepRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StepId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StepId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args[:0], dAtA[iNdEx:postIndex]...)
			if m.Args == nil {
				m.Args = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TryStepResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TryStepResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TryStepResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StepId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StepId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfirmTransRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfirmTransRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfirmTransRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfirmTransResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfirmTransResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfirmTransResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelTransRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelTransRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelTransRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelTransResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelTransResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelTransResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelTransSuccessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelTransSuccessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelTransSuccessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CancelTransSuccessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CancelTransSuccessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CancelTransSuccessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTransRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTransRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTransRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetTransResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetTransResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetTransResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Transaction == nil {
				m.Transaction = &Transaction{}
			}
			if err := m.Transaction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetExpiredTransListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetExpiredTransListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetExpiredTransListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopN", wireType)
			}
			m.TopN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopN |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetExpiredTransListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetExpiredTransListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetExpiredTransListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransUniqIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransUniqIds = append(m.TransUniqIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRollingBackTransListRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRollingBackTransListRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRollingBackTransListRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopN", wireType)
			}
			m.TopN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TopN |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRollingBackTransListResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRollingBackTransListResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRollingBackTransListResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, &Transaction{})
			if err := m.Transactions[len(m.Transactions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTccCoordinator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTccCoordinator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTccCoordinator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTccCoordinator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTccCoordinator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTccCoordinator
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTccCoordinator
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTccCoordinator(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTccCoordinator = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTccCoordinator   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("tcc_coordinator.proto", fileDescriptorTccCoordinator) }

var fileDescriptorTccCoordinator = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdb, 0x8e, 0xe3, 0x44,
	0x10, 0xdd, 0x4e, 0xe6, 0x92, 0xa9, 0xcc, 0xc5, 0xd3, 0x13, 0xb2, 0x1e, 0xaf, 0x08, 0x91, 0x85,
	0x50, 0x58, 0x96, 0x80, 0xb2, 0x17, 0x2e, 0xd2, 0x4a, 0x4c, 0xc2, 0xec, 0x10, 0x2e, 0x03, 0x72,
	0xb2, 0x12, 0xe2, 0x01, 0xf0, 0xb6, 0x7b, 0x46, 0x2d, 0x12, 0xb7, 0xd7, 0xee, 0xac, 0x76, 0x5e,
	0x90, 0x90, 0xf8, 0x00, 0xfe, 0x82, 0x07, 0xe0, 0x03, 0x10, 0x3f, 0x80, 0x84, 0x90, 0xf8, 0x04,
	0x94, 0x2f, 0x41, 0x6e, 0xf7, 0x90, 0x76, 0x9c, 0x78, 0x9d, 0xd5, 0x20, 0xf1, 0x96, 0xae, 0xae,
	0x73, 0xaa, 0x4e, 0x75, 0x55, 0x59, 0x81, 0x17, 0x04, 0x21, 0x5f, 0x11, 0xce, 0x43, 0x8f, 0xf9,
	0xae, 0xe0, 0x61, 0x3b, 0x08, 0xb9, 0xe0, 0xf8, 0x30, 0xe2, 0x67, 0x42, 0x84, 0xae, 0x1f, 0xb5,
	0xf5, 0x4b, 0x41, 0x88, 0xfd, 0x10, 0x76, 0x86, 0xf1, 0x85, 0x4b, 0x04, 0xe3, 0x7e, 0xdf, 0xc3,
	0x35, 0x58, 0x77, 0x83, 0xa0, 0xef, 0x99, 0xa8, 0x89, 0x5a, 0x5b, 0x4e, 0x72, 0xc0, 0x26, 0x6c,
	0x3e, 0x9a, 0x44, 0x3d, 0xee, 0x51, 0xb3, 0x24, 0xed, 0x97, 0xc7, 0xd8, 0x5f, 0x84, 0x4f, 0xfb,
	0x9e, 0x59, 0x4e, 0xfc, 0xe5, 0xc1, 0xbe, 0x0f, 0x7b, 0x1a, 0xed, 0x40, 0xd0, 0x00, 0xd7, 0x61,
	0x23, 0x12, 0x74, 0xc6, 0xac, 0x4e, 0x18, 0xc3, 0xda, 0x51, 0x78, 0x1e, 0x49, 0xde, 0x6d, 0x47,
	0xfe, 0xb6, 0xa7, 0x25, 0xa8, 0x6a, 0x78, 0x7c, 0x0a, 0x3b, 0x42, 0xcf, 0x52, 0x52, 0x54, 0x3b,
	0xad, 0xf6, 0x52, 0x61, 0xed, 0x94, 0x2a, 0x27, 0x0d, 0xc7, 0x4d, 0xa8, 0x4a, 0xc3, 0x43, 0x9f,
	0x3d, 0xee, 0x7b, 0x4a, 0x92, 0x6e, 0xc2, 0xef, 0xc1, 0x7a, 0x9c, 0x5f, 0x64, 0x96, 0x9b, 0xe5,
	0x56, 0xb5, 0x73, 0xb3, 0x58, 0xa4, 0x58, 0xa8, 0x93, 0x00, 0xf1, 0x67, 0xb1, 0x5e, 0x57, 0x4c,
	0x22, 0x73, 0xad, 0x89, 0x5a, 0xbb, 0x9d, 0xb7, 0x8b, 0x51, 0xa4, 0xe9, 0x62, 0xbc, 0xa3, 0x78,
	0xec, 0x4f, 0x60, 0x3f, 0x73, 0x89, 0x2b, 0xb0, 0xd6, 0xf7, 0x99, 0x30, 0xae, 0xe1, 0x1d, 0xd8,
	0xea, 0xf1, 0xf1, 0x98, 0x09, 0x41, 0x3d, 0x03, 0xf0, 0x1e, 0x54, 0x1d, 0x3e, 0x1a, 0x31, 0xff,
	0xbc, 0xeb, 0x92, 0x6f, 0x8c, 0x1a, 0xde, 0x05, 0x88, 0x0d, 0xd4, 0x93, 0xe7, 0x96, 0xfd, 0x0b,
	0x82, 0xfd, 0x2e, 0x3d, 0x67, 0xbe, 0x24, 0x75, 0xe8, 0xe3, 0x09, 0x8d, 0xc4, 0x95, 0x97, 0xda,
	0x82, 0xca, 0x99, 0xcb, 0x46, 0x0f, 0xdc, 0x48, 0xc8, 0x3a, 0x57, 0x9c, 0x7f, 0xcf, 0xf8, 0x16,
	0xec, 0xd3, 0xa7, 0x01, 0x0b, 0xe9, 0x90, 0x8d, 0xe9, 0x80, 0x12, 0xee, 0x7b, 0x91, 0xec, 0xa3,
	0x75, 0x27, 0x7b, 0x61, 0xff, 0x88, 0x00, 0xeb, 0xf9, 0x46, 0x01, 0xf7, 0x23, 0x3a, 0xff, 0x96,
	0x28, 0xf3, 0x96, 0x36, 0x87, 0x1b, 0x59, 0xdc, 0x71, 0x18, 0xf2, 0x50, 0x76, 0xf0, 0x06, 0x94,
	0x3e, 0xfd, 0xc8, 0xb8, 0x86, 0x0d, 0xd8, 0xee, 0xfb, 0x4f, 0xdc, 0x11, 0xf3, 0x8e, 0xe2, 0x9e,
	0x37, 0x50, 0x6c, 0x39, 0x1e, 0x07, 0xe2, 0xa2, 0x9b, 0xf4, 0xba, 0x51, 0x8a, 0x6b, 0x28, 0x2d,
	0x43, 0xe7, 0xf3, 0xbe, 0x67, 0x94, 0x71, 0x0d, 0x8c, 0xf7, 0x27, 0xc1, 0x88, 0x11, 0x57, 0x50,
	0x55, 0x41, 0x03, 0xec, 0x2f, 0x61, 0x77, 0x18, 0x5e, 0xc8, 0x66, 0x50, 0x55, 0x7d, 0x66, 0x92,
	0xda, 0x78, 0x94, 0x16, 0x8e, 0x47, 0x59, 0x1b, 0x8f, 0x3f, 0x50, 0x3c, 0x5e, 0x2a, 0x40, 0xd1,
	0x32, 0x2c, 0x8b, 0x60, 0x7f, 0x0b, 0xe6, 0x1c, 0x59, 0xb6, 0x36, 0x35, 0x30, 0x12, 0xdd, 0x33,
	0x3e, 0x03, 0xc5, 0x2d, 0x26, 0xad, 0x03, 0x49, 0x64, 0x94, 0xf0, 0x75, 0x38, 0xd0, 0x9a, 0xe1,
	0x94, 0x8b, 0x07, 0x7c, 0xe2, 0xc7, 0xcd, 0x68, 0x41, 0x3d, 0xd3, 0xba, 0x32, 0x8a, 0x51, 0xb5,
	0xdf, 0x82, 0x83, 0x1e, 0xf7, 0xcf, 0x58, 0x38, 0x4e, 0x35, 0xe2, 0xb3, 0xdf, 0xf5, 0x67, 0x04,
	0xb5, 0x34, 0xb2, 0x70, 0x4b, 0x84, 0xf0, 0xe2, 0x22, 0x64, 0x51, 0xe1, 0xcf, 0xa5, 0xf3, 0x1e,
	0xe0, 0x9e, 0xeb, 0x13, 0x3a, 0x5a, 0x51, 0xe6, 0x4f, 0x08, 0x0e, 0x52, 0xc0, 0xff, 0xb5, 0xca,
	0xfb, 0x70, 0xa8, 0x25, 0x3b, 0x98, 0x10, 0x42, 0xa3, 0x15, 0xc4, 0xfe, 0x8a, 0xc0, 0x5a, 0x84,
	0x2f, 0xac, 0xf9, 0x02, 0x5e, 0xd6, 0x35, 0xcf, 0x11, 0xfc, 0xa7, 0xd2, 0x6f, 0xc3, 0xde, 0x09,
	0x15, 0x2b, 0xbe, 0xee, 0x9f, 0x08, 0x8c, 0x19, 0x4a, 0xc9, 0xfc, 0x40, 0xc1, 0x92, 0x28, 0x6a,
	0x05, 0xbf, 0x52, 0x6c, 0x05, 0x3b, 0x3a, 0xd4, 0xe6, 0x70, 0x38, 0xcf, 0x7e, 0x35, 0x9b, 0xaf,
	0x0e, 0x58, 0x61, 0xf4, 0xca, 0x81, 0xfd, 0x26, 0x58, 0x27, 0x54, 0x1c, 0xcb, 0xed, 0x9d, 0x5c,
	0x7d, 0xcc, 0x22, 0x71, 0x59, 0x0f, 0x0c, 0x6b, 0x82, 0x07, 0xa7, 0x52, 0xd1, 0xba, 0x23, 0x7f,
	0xdb, 0x47, 0x70, 0x63, 0x21, 0x42, 0xd5, 0xc2, 0x86, 0x6d, 0xad, 0x5e, 0x91, 0x89, 0x9a, 0xe5,
	0xd6, 0x96, 0x93, 0xb2, 0xd9, 0x77, 0xa0, 0x71, 0x42, 0x85, 0xf6, 0xb9, 0x2b, 0x14, 0x78, 0x0c,
	0x2f, 0x2d, 0x45, 0xa9, 0xe0, 0x1f, 0xaa, 0xe0, 0x49, 0x35, 0x93, 0xe0, 0xc5, 0x5f, 0x22, 0x85,
	0xed, 0xfc, 0xb6, 0x09, 0x30, 0xec, 0xf5, 0x06, 0x34, 0x7c, 0xc2, 0x08, 0xc5, 0x0c, 0x60, 0xf6,
	0x55, 0xc2, 0xb7, 0x72, 0x28, 0x33, 0x1f, 0x69, 0xeb, 0xf5, 0x82, 0xde, 0x4a, 0xc5, 0xd7, 0xb0,
	0xa9, 0x36, 0x3c, 0x7e, 0x35, 0x37, 0x75, 0xfd, 0x9b, 0x65, 0xdd, 0x2c, 0xe2, 0xaa, 0x22, 0x70,
	0xd8, 0xd6, 0xa7, 0x0e, 0xb7, 0x73, 0xb0, 0x0b, 0x96, 0xbd, 0xf5, 0x46, 0x61, 0x7f, 0x15, 0x70,
	0x04, 0x55, 0x6d, 0x4d, 0xe0, 0xbc, 0x82, 0x64, 0x97, 0xae, 0xd5, 0x2e, 0xea, 0xae, 0xa2, 0x7d,
	0x87, 0x52, 0xbb, 0x5b, 0x2d, 0x15, 0x7c, 0xa7, 0x18, 0x4d, 0x7a, 0x09, 0x5a, 0x77, 0x57, 0x44,
	0xa9, 0x1c, 0x08, 0x54, 0x2e, 0x27, 0x19, 0xe7, 0x3d, 0xcd, 0xdc, 0x0a, 0xb2, 0x5e, 0x2b, 0xe4,
	0xab, 0x82, 0x7c, 0x8f, 0xe0, 0x60, 0xc1, 0x30, 0xe2, 0xbb, 0xf9, 0x24, 0x4b, 0xc6, 0xdd, 0xba,
	0xb7, 0x2a, 0x4c, 0xa5, 0xf1, 0x03, 0x82, 0xeb, 0x4b, 0x46, 0x13, 0xbf, 0x93, 0xcf, 0x99, 0xb3,
	0x04, 0xac, 0x77, 0x9f, 0x07, 0x9a, 0xa4, 0xd4, 0xad, 0xff, 0x3e, 0x6d, 0xa0, 0xbf, 0xa6, 0x0d,
	0xf4, 0xf7, 0xb4, 0x81, 0xbe, 0xa8, 0x10, 0xee, 0x8b, 0xd0, 0x25, 0xe2, 0xd1, 0x86, 0xfc, 0x8b,
	0x75, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x96, 0x8d, 0x6d, 0x7b, 0x0d, 0x00, 0x00,
}
